spring.application.name=mongo-rbac-engine
# MongoDB
spring.data.mongodb.uri=mongodb+srv://<user>:<pass>@<endpoint>.mongodb.net/?appName=devrel-tutorial-java-rbac-foojay
spring.data.mongodb.database=rbac_engine
# Disable Spring Security in-memory user auto-configuration
spring.security.user.name=disabled
spring.security.user.password=disabled
# JWT
jwt.secret=4d6f6e676f52626163456e67696e655365637265744b657932303236212121
jwt.expiration-ms=86400000